### ISSUE TITLE
Read current browser cache 

### ISSUE THREAD

**Issue by justbuzer** [d3rt0xx/FlyffDroid#3]
Hi.
I really like this project.
Can you make it read my current browser (Chrome) cache?
Because every time I start, it download the game resources from the beginning. It would be great if it can load from the current browser's cache.
Thank you.

**Comment by d3rt0xx** [comment]
Hi!

AppCache has been added in FlyffDroid 1.0.6 release today. Hope this will fix your problem 👍

Please give feedback

**Comment by justbuzer** [comment]
Still don't work for me. The app still downloading game resources every time it start. App size in the app info also showing cache 22MB which is looks way too small for this game I think. I have big amount of space left on my internal storage.

![Screenshot_2022-08-05-09-22-47-36](https://user-images.githubusercontent.com/18571571/182988081-9eb9eb6b-3c85-4f8b-8e7f-c65f676dddaf.jpg)

Oh in case you need, I'm using OPPO F7 phone. Android 10. ColosOS (official OS for OPPO phone).

**Comment by d3rt0xx** [comment]
It's normal! You cannot download the whole game at once since it is streamed to your device. Cache should be bigger and bigger over time.
