### ISSUE TITLE
Signing In Using Facebook

### ISSUE THREAD

**Issue by rebibeMee** [d3rt0xx/FlyffDroid#6]
Internal Server Error occured when signing in via facebook

**Comment by d3rt0xx** [comment]
Try to reload the client and report.

**Comment by rebibeMee** [comment]
I tried it but still cannot log in... i find your app more useful than [FlyffUAndroid](https://github.com/ils94/FlyffUAndroid) made by [ils94](https://github.com/ils94) hope you fix it...

**Comment by d3rt0xx** [comment]
I'll take a deeper look on it. Thank you for your feedback 🙂

**Comment by Kvothe1997** [comment]
Is this a common problem? I can't log in with Google either.  I have the  same problem with #FlyffUAndroid :(

**Comment by d3rt0xx** [comment]
It's a common problem, yes. So far there is no solution for this :cry: I think it is due to the API of Google or Facebook...

**Comment by d3rt0xx** [comment]
After some research there is no solution for this issue.

**Comment by gabreek** [comment]
I found a "solution", whenever you get 500 internal error, press play now button then start with a guest character, open your character page and select to link the account, it will redirect to login page again then you just have to press the facebook or Google login button and it will login

**Comment by gabreek** [comment]
After you've logged on as far you don't clean app cache or change webview options login will work on both clients np
