### ISSUE TITLE
Immersive fullscreen

### ISSUE THREAD

**Issue by gabreek** [d3rt0xx/FlyffDroid#7]
Could you please update for it to use immersive full screen for phones with notch and infinite screen?

**Comment by d3rt0xx** [comment]
You can change these in your Android settings. Check your display settings. You often find this settings under "Display" or "Screen -> "Immersive Mode" or "Fullscreen Apps"

**Comment by gabreek** [comment]
I've set, and am even using magisk setappfull but whenever I exit fullscreen to open second client it comes back to non immersive mode, it won't stay unless immersive flag is specified

**Comment by d3rt0xx** [comment]
I'll take a look this weekend. Stay tuned please

**Comment by gabreek** [comment]
Thank you!

**Comment by d3rt0xx** [comment]
@gabreek I may have found a solution and would be happy if you could test it. Please message me on Discord: d3rt0xx#2109

**Comment by d3rt0xx** [comment]
Fixed with update 1.1.5 (Pull #9)

**Comment by d3rt0xx** [comment]
Fixed with update 1.1.5 (Pull #9)
