### ISSUE TITLE
Can't see my itens

### ISSUE THREAD

**Issue by gabreek** [d3rt0xx/FlyffDroid#8]
Using any browser seems to work normally but with your app my character equiped itens and preview occupies the whole screen as you can see the comparation in this link, changing scale has no effect

https://photos.app.goo.gl/1xfpoy3635j5ou8Q7

**Comment by d3rt0xx** [comment]
Your screen resolution is too small. Depends on your other issue #7

**Comment by gabreek** [comment]
My phone's resolution is 1080x2440 and works normally if I'm not in fullscreen in browsers

**Comment by d3rt0xx** [comment]
Maybe this "bug" will gone when issue #7 is fixed. We will see. Stay tuned

**Comment by d3rt0xx** [comment]
Fixed with update 1.1.5 (Pull #9)
